sudo: false

language: python

python:
    - "2.6"
    - "2.7"

install:
    - pip install -e .

script:
    - trial tests/*_test.py
    - twistd -y bin/mailingset.tac
    - kill $(cat twistd.pid)

notifications:
    email: false
